language: go
sudo: require
dist: trusty
go:
  - 1.9.2

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
      
before_install:
  - sudo service mysql restart
  - mysql -e 'create database canyonsysu;'
  - go get -v
  - go test -v ./service